name: Infrastructure destroy (infrastructure-down)
# Trigger deployment only on push to main branch
on:
  push:
    branches:
      - infrastructure-down

jobs:
  build:
    name: Destroy resources
    runs-on: ubuntu-latest
    permissions: write-all
    env: 
      RUN_NUMBER: ${{ github.run_number }}
    steps:
      - name: Login to Vultr Instance and run terraform plan
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VULTR_INSTANCE_IP }}
          username: ${{ secrets.VULTR_INSTANCE_USER }}
          key: ${{ secrets.VULTR_INSTANCE_KEY }}
          script: |
            cd devops-training/lambda-deploy-example-bastion
            terraform init
            terraform destroy -auto-approve 
      - name: Add the infratag
        uses: actions/github-script@v7
        with:
          result-encoding: string
          retries: 1
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/v-destroy.${{github.run_number}}',
              sha: context.sha
            })